### ISSUE TITLE
How to set height use unit mm

### ISSUE THREAD

**Issue by czewail** [jshor/symbology#101]
How to set height use unit mm?

like
```js
 const { data } = await createStream({
                symbology: SymbologyType.EANX,
                backgroundColor: 'FFFFFFFF',
                height: '100mm'
            }, ele.content, OutputType.SVG);
```

**Comment by jshor** [comment]
The [`height` param](https://symbology.dev/docs/options.html#height) only uses pixels. If you want to use millimeters, you could export it as an SVG or PostScript file and modify it to specify that height.
