### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by claridgicus** [jshor/symbology#120]
Super useful package - but I can't run it in lambda at the moment because I've migrated to 18, so a generic request please for the package to support node 18.

**Comment by mividtim** [comment]
+1 I'm moving to Node 20 on Oct 24th (when it enters LTS). Why is nodejs even capped in engines? There's a symbology_18 published that raises the cap to support Node 18, but not 19 or 20. It's quite unusual for an NPM package to have a hard cap, unless there's an incompatibility.

**Comment by mividtim** [comment]
I just verified that I can clone, update engines to <= 21, build, and `yarn test` successfully.

**Comment by mividtim** [comment]
Is there any way I can help, here? I'd be happy to provide a PR, given some direction on how to accomplish the goal. It seems that the binary build may be part of the issue. The README is a bit light on how to contribute. Thanks!

**Comment by fenny-mdg** [comment]
+1
I migrated to node 18 and my lambda could not run anymore
I got this error 
` node_modules/symbology/bin/binding/bin/symbology.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 108. This version of Node.js requires\nNODE_MODULE_VERSION 83. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).`

I tried by removing package-lock.json and node_modules and then re-install with npm install but nothing works 
I tried to rebuild but same error 

A support of node js 18+ will be really apprecied and usefull , thanks

**Comment by hatsantos** [comment]
Same issue here... When installing in a new project:

npm i symbology

I get this error:

`npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'symbology@3.0.13',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.18.1', npm: '9.8.1' }
npm WARN EBADENGINE }
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\_git\\InternalProjects\\barcodes\\node_modules\\@mapbox',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\_git\InternalProjects\barcodes\node_modules\@mapbox\node-pre-gyp\node_modules\make-dir\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\_git\\InternalProjects\\barcodes\\node_modules\\@mapbox\\node-pre-gyp\\node_modules\\make-dir\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1`

**Comment by mividtim** [comment]
Node 16 reaches end of life on September 11 (i.e. in less than a month). There are at least two unofficial re-releases of symbology that support Node 18 (symbology-18 and symbology-plus). Also, note that Node 18 entered Maintenance mode on October 18 (a few days ago), and Node 20 enters long-term support (i.e. recommended for production) on October 24 (tomorrow). Do the maintainers of this package plan to keep up with Node version recommendations? Node 16 is _no longer recommended for production_, and even Node 18 is no longer the recommended version: Node 20 is. Should the developer community using Symbology in production embrace one of the forks?

**Comment by jshor** [comment]
Node v18 and v20 are supported as of v4.0.0

**Comment by mividtim** [comment]
Thank you so much, @jshor !! Super appreciate this!
