### ISSUE TITLE
Readme documentation has outdated links

### ISSUE THREAD

**Issue by GeorgeWL** [jshor/symbology#15]
There's quite a few, here's some:

https://github.com/jshor/symbology#enumerated-barcode-types doesn't link to anywhere - I assume it's meant to link here : https://github.com/jshor/symbology/wiki/Barcode-types

https://github.com/jshor/symbology#711-prerequisites doesn't link to anywhere, I am also not sure where it's meant to link to.

**Comment by jshor** [comment]
Thanks @GeorgeWL - links and info have been updated
