### ISSUE TITLE
"TypeError: stream is undefined" when used with ReactJS

### ISSUE THREAD

**Issue by andygock** [jshor/symbology#33]
Hi,

I tried using this with ReactJS, but can not import the library.

Demo: <https://codesandbox.io/s/elated-bartik-tez9w>

Andy

**Comment by jshor** [comment]
Unfortunately, Symbology is a [native Node.js module](https://blog.risingstack.com/writing-native-node-js-modules/) and can only be run in Node.js. More info about that [here](https://symbology.dev/docs/development.html).
