### ISSUE TITLE
Update npm to latest version?

### ISSUE THREAD

**Issue by john-doherty** [jshor/symbology#40]
Please can you update npm to the latest version? TY

**Comment by john-doherty** [comment]
Hey @jshor, any chance of getting this published?

**Comment by jshor** [comment]
Sorry about that @john-doherty, looks like something's wrong with `npm publish`. Both manually and in CI, it says 1.18 is published, but I don't see it on npm.

I'll investigate this. For now, you can use `npm install jshor/symbology#1.18.0`, or `yarn add jshor/symbology#1.18.0` until this gets fixed.

**Comment by jshor** [comment]
@john-doherty 1.18 is now on npm

**Comment by john-doherty** [comment]
Thanks Josh. I pulled the latest version, but it throws the following error:

```bash
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /tmp/build/node_modules/symbology/node_modules/.tar.DELETE/node_modules/.bin
npm ERR! dest /tmp/build/node_modules/symbology/node_modules/tar/node_modules/.bin
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/tmp/build/node_modules/symbology/node_modules/.tar.DELETE/node_modules/.bin' -> '/tmp/build/node_modules/symbology/node_modules/tar/node_modules/.bin'
```

Any ideas?

**Comment by jshor** [comment]
I was able to install symbology@1.18.0 from npm without an issue on Windows. What OS/platform are you trying this on?

You could try the following:

* if you have `symbology` already installed, try removing it and reinstalling, or
* `npm rebuild`, or
* `rm -rf node_modules/symbology` and install again

**Comment by john-doherty** [comment]
I can install it locally on a mac, works fine. This error appears when I try to run `npm install` on Ubuntu 18.04.3

**Comment by john-doherty** [comment]
Found the issue `node-pre-gyp` did not exist. I fixed it by adding it to my project:

```bash
npm install --save node-pre-gyp
```

Thanks for your help!
