### ISSUE TITLE
Outdated Zint library

### ISSUE THREAD

**Issue by woo-j** [jshor/symbology#46]
Hi - I've just noticed your project which looks like a fantastic extension to the Zint library, but you seem to be using an outdated version of that library. Zint is still being actively developed on Sourceforge at

https://sourceforge.net/projects/zint/

and there is a github mirror of the code at:

https://github.com/woo-j/zint

The latest version includes many bugfixes and new functionality which would also you to close tickets #31 #32 and #35.

**Comment by jshor** [comment]
@woo-j, the legend himself! Thanks so much for your massive contribution to the OSS community and for your maintenance on this terrific library!

I'll update symbology very soon to reflect the updates to zint, as well as the API to support the new features of zint
