### ISSUE TITLE
CreateFile

### ISSUE THREAD

**Issue by ecropolis** [jshor/symbology#5]
The type param is not passed. I see in documentation it's available in the call to createStream(Symbol, data, type). In createFile() it's not listed but the documentation indicates that png, svg and eps are available options. Looking at the createFile function I don't see the type being passed along.

**Comment by jshor** [comment]
@ecropolis Thanks for catching this. The `type` param should be removed from `createStream` in the documentation. Unfortunately at the moment the Zint library will only stream bitmap, so it will only return a png.

As for `createFile()`, it will create an svg, eps or png file based on the file extension you pass in using the `fileName` property in the `Symbol` struct. This is also due to the way Zint implements the file creation method. I'll also add this info to the readme.

I plan to fix both of these issues, but I need to modify Zint to do this.

**Comment by ecropolis** [comment]
Sounds good. I guess my implementation just isn't working anyway. I'm
basically just sending the example but I get an error. I think it was a 6 -
no input data. The binaries all seemed to build fine on my Raspberry Pi3
running minibian. I was really hoping to use this because I could pipe an
eps right to the printer! - I did find another lib that outputs a png and
then used imagemagick to position it on to a PDF; and that all seems like
it will work very well actually. Figured now that I'm in imagemagick - I
could also add a little branding to my output. Any suggestions on that
error though would be great - I'm definitely not set in stone on anything
yet.


*Warren Gwartney*Founder & Principal @Ecropolis <http://ecropolis.com>

Superhero { webDevelopers } <https://superheroic.ly> - Recruiting
Superheroic Web Developers
Superhero Codecamp <https://superherocode.camp> - Teaching Young People how
to Code
*(214) 945-0505*

**Comment by jshor** [comment]
@ecropolis Would you mind sharing the code you used? I just tried out the example for createStream and it seems to work as expected.

Using:

```
const symbology = require('symbology');

symbology
  .createStream(Symbol, '12345')
  .then((data) => {
    console.log('Result: ', data);
  },(err) => {
    console.log('Error: ', err);
  });
```

Results in:

```
Result:  { data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJ4AAAB2CAYAAAA5kiqUAAAAAklEQVR4AewaftIAAAJeSURBVO3BUW5cRxAEwazG3v9cvFUZA0PQgH6iaBtQf2xGpO0HlyQcbTmScGvLkyTc2nIk4WjLLQm3tjxJwq0tRxKetOVIwtGWWxKetOVIwtGWryThaMuTJBxtuSXhaMuTJNzaciTh1pYnSTjaciThaMstCU/ackvCk7Y8ScLRliMJR1tug7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oJBWjBICwZpwSAtGKQFg7RgkBYM0oIAH0h/2CAtGKQFL0RbknBryy0JR1ueJOGztiThaMuTJLyjF2+uLZ+1JQm3tiQhCZ+15bO2fJYE/W14Y21Jwv/RliTc2pIE/dqLN5aEJ0n4jrYk4bvackvCu3qh32pLEm5tOdqShB/akoQnSbi1JQnv6IX+kyT80JYkfCUJ+mnQl9qShO9oSxL0e4N+qS1JuLXlK21pS1uOthxt0U8v9KgtSfg3knBrSxL0TwE+eFNt+SwJbXmShKMttyQ8aUsSfmjLLQnvKsAH0h82SAsGacEgLRikBX8B62G1DJc00xYAAAAASUVORK5CYII=',
  width: 158,
  height: 118,
  message: '',
  code: 0 }
```

**Comment by girishassudanizeon** [comment]
Hello,
I am also trying to use this but getting result as 

Result:  { inputData: '', message: 'error: No input data', code: 6 }

My Example code:
var symbology = require('symbology');

var Symbol = {
    symbology: symbology.Barcode.CODE128,
    foregroundColor: 'fff000',
    backgroundColor: '000000',
    fileName: '/barcode.png'
};

symbology
    .createStream(Symbol, '12345')
    .then(function(data) {
        console.log('Result: ', data);
    }, function(err) {
        console.log('Error: ', err);
    });
