### ISSUE TITLE
Node 17x Error

### ISSUE THREAD

**Issue by talkquazi** [jshor/symbology#84]
When installing symbology with node v17+ the following error occurs. 

`error symbology@3.0.6: The engine "node" is incompatible with this module. Expected version ">=14.0.0 <17.0.0". Got "17.0.1"`

Suggestion:
Maybe don't set a hard node version limit in the package manifest.

**Comment by jshor** [comment]
Thanks for reporting @talkquazi - as you pointed out node v17+ is not yet supported by symbology, but I hope to have it supported soon
