### ISSUE TITLE
How to resize generated image

### ISSUE THREAD

**Issue by MatteoGauthier** [jshor/symbology#92]
Hey I want to resize a qr code, the output is 48x48 how can I upscale it ?

Thanks for this lib however

**Comment by jshor** [comment]
To resize any symbology, there are a couple of options:

1. You can render it as a PNG, you can set the [`height`](https://symbology.dev/docs/options.html#height) option to whatever height you want in pixels (the width ratio will upscale accordingly).
2. You can render it as a scalable graphic (PostScript or SVG) and scale it in whatever application it's used in
