### ISSUE TITLE
App crashes when generating barcode with SVG output

### ISSUE THREAD

**Issue by hatsantos** [jshor/symbology#96]
I have a script in nodejs to generate some PDF files. Each page must have a barcode, so I'm using symbology to generate the barcode in the SVG format and add it to each PDF page.

This is working ok, so far, but now I had to generate a large number of pages.

I need to run 3000 times, but the app crashes every time at iteration 509/510.
I isolated the code and simply running the function that returns the barcode SVG string make the app crash.

This seems to happen if the output is SVG. If the output is set to PNG the app runs all the iterations that I tested (1000 / 2000 and 3000).

```
/**
 * Returns an SVG string of a CODE39 barcode.
 * @param value string: barcode value.
 * @returns 
 */
const getBarCode = async (value:string):Promise<string> =>
{
    try 
    {
        const { data } = await createStream
        (
            { 
                symbology: SymbologyType.CODE39, 
                showHumanReadableText: true,
                height: 190, 
                scale: 1
            },
            value,
            OutputType.SVG
        );
    
        return data; 
    } 
    catch (error) 
    {
        throw error;
    }
}

/**
 * Render a number of pages corresponding to totalPages number.
 * @param totalPages: number total pages to render
 */
const generatePages = async (totalPages:number) => 
{
    console.time('Time Rendering');

    try 
    {
        const pages = [...Array(totalPages).keys()].map(page => (page + 1).toString().padStart(4, '0'));
        
        for (const [index, value] of pages.entries()) 
        {
            console.log('Barcode to page: ', value);
            await getBarCode(value);
        }

        console.timeEnd('Time Rendering');
    } 
    catch (error) 
    {
        throw error;
    }
}

//Starts to generate n pages
generatePages(1000);
```

I'm using node **v16.14.0** and the latest version of this lib: **v3.0.8**

**Comment by HitomiTenshi** [comment]
I just encountered the same problem with node **v16.16.0** and the latest version of this lib: **v3.0.8**. Using PNG output instead of SVG output solves the crash.
